import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "../../(main)/globals.css";
import { TbShoppingBag } from "react-icons/tb";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="py-5.25 px-9.5 flex justify-center items-center gap-9.5 border border-[#DEDEDE]">
          <div className="heading flex-1 text-center text-[22px] font-medium">Ostrich</div>
          <Link href={"/cart"}>
            <TbShoppingBag size={24} />
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
